# Change these first
owner: HiWay-Media # Your GitHub organization or username, where this repository lives
repo: status-check # The name of this repository

sites:
  - name: Hiway Media website
    url: https://hiway.media
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: hiway.media
  baseUrl: https://hiway-media.github.io/status-check/
  logoUrl: https://github.com/HiWay-Media/status-check/blob/master/assets/logo_white.png?raw=true
  name: Status HiWay Media
  introTitle: "**HiWay Media** Status Dashboard."
  introMessage: " "
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

commitMessages:
  commitAuthorName: "HiWay Media"
  commitAuthorEmail: "github-bot@hiway.media"

i18n:
  footer: "If you are experiencing an issue not listed here, please [contact support](mailto:support@hiway.media)."
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
